dist: xenial
language: cpp
compiler: clang

# safelist
branches:
  only:
    - master

before_script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug

script:
  # Check if the application builds.
  - make -j

  # Run the tests
  - make -j test_main
  - ctest --verbose
