dist: xenial
language: cpp
compiler: clang

# safelist
branches:
  only:
    - master

before_script:
  - cmake -S . -B build

script:
  - cmake --build build --parallel --target test
  - ./build/test/test
